[appearance]
base_page_title = "Studentorchesteret Dei Taktlause"
primary_color = "#A50105"
favicon = "images/taktlausfavicon.ico"

[appearance.navbar]
logo = "images/taktlauslogo.svg"
logo_santa_hat = "images/taktlauslogo_santa_hat.svg"
title = "Studentorchesteret Dei Taktlause"
title_short = "Dei Taktlause"
development_background_color = "#058104"

[initial_data]
orchestra_name = "Studentorchesteret Dei Taktlause"

[initial_data.superuser]
email = "vevansvarleg@taktlaus.no"

[initial_data.site]
domain = "taktlaus.no"

[readme]
project_title = "Taktlausveven"
orchestra_name = "Studentorchesteret Dei Taktlause"

[production.server.nginx]
http_server_name = "taktlaus.no www.taktlaus.no"
https_server_name = "taktlaus.no www.taktlaus.no"
website_name = "taktlausveven"
